$content = Get-Content -Raw -Encoding UTF8 README.md
$replacements = @(
    @("<h1>🧠 Agentic AI with LangGraph</h1>", "<h1>Agentic AI with LangGraph</h1>"),
    @("## 🔍 What is This?", "## What is This?"),
    @("## 🧬 GenAI vs Agentic AI — Why Agents?", "## GenAI vs Agentic AI — Why Agents?"),
    @("## 🏛️ Architecture", "## Architecture"),
    @("## 🛣️ Roadmap", "## Roadmap"),
    @("## 📚 Curriculum", "## Curriculum"),
    @("### 🎓 Learning Path", "### Learning Path"),
    @("## 📓 Notebook Index", "## Notebook Index"),
    @("### 🟢 Phase 1 — Foundations", "### Phase 1 — Foundations"),
    @("### 🔵 Phase 2 — Workflow Patterns", "### Phase 2 — Workflow Patterns"),
    @("### 🟡 Phase 3 — Chatbots & Persistence", "### Phase 3 — Chatbots & Persistence"),
    @("### 🟠 Phase 4 — Tools, MCP & RAG", "### Phase 4 — Tools, MCP & RAG"),
    @("### 🔴 Phase 5 — Advanced & Production", "### Phase 5 — Advanced & Production"),
    @("## 📂 Project Structure", "## Project Structure"),
    @("## 🚀 Quick Start", "## Quick Start"),
    @("### ⚙️ Installation", "### Installation"),
    @("### 🔑 Configuration", "### Configuration"),
    @("### ⚡ Your First Agent", "### Your First Agent"),
    @("## 🛠️ Tech Stack", "## Tech Stack"),
    @("## 🤝 Contributing", "## Contributing"),
    @("## 📄 License", "## License"),
    @("| ✅ |", "| Done |"),
    @("| 🔜 | ⏳ Coming Soon |", "| WIP | Coming Soon |"),
    @("├── 📘 01_Foundation_of_AgenticAI", "├── 01_Foundation_of_AgenticAI"),
    @("├── ⛓️ 02_Sequential_&_Parallel_workflow", "├── 02_Sequential_&_Parallel_workflow"),
    @("├── 🔀 03_Conditional_Workflow", "├── 03_Conditional_Workflow"),
    @("├── 🔄 04_Iterative_Workflows", "├── 04_Iterative_Workflows"),
    @("├── 💬 05_Structured_ai_chatbot", "├── 05_Structured_ai_chatbot"),
    @("├── 🖥️ 06_Conversational_ai_chatbot", "├── 06_Conversational_ai_chatbot"),
    @("├── 🔍 07_LangsSmith", "├── 07_LangsSmith"),
    @("├── 📊 08_Observability_in_LangGraph", "├── 08_Observability_in_LangGraph"),
    @("├── 🔧 09_Tools_in_LangGraph", "├── 09_Tools_in_LangGraph"),
    @("├── 📡 10_MCP_Client", "├── 10_MCP_Client"),
    @("├── 📚 11_RAG_using_LangGraph", "├── 11_RAG_using_LangGraph"),
    @("├── 🙋 12_Human_in_the_Loop", "├── 12_Human_in_the_Loop"),
    @("├── 🧩 13_Subgraphs", "├── 13_Subgraphs"),
    @("├── 🧠 14_Memory_in_LangGraph", "├── 14_Memory_in_LangGraph"),
    @("├── 🏗️ 15_Projects", "├── 15_Projects"),
    @("(🔜)", "(WIP)"),
    @("🎯 Planner:", "[Planner]:"),
    @("⚡ Executor:", "[Executor]:"),
    @("✅ Reviewer:", "[Reviewer]:"),
    @("🚀 User:", "[User]:"),
    @("<td><b>🧠 Core Framework</b></td>", "<td><b>Core Framework</b></td>"),
    @("<td><b>🤖 LLM Providers</b></td>", "<td><b>LLM Providers</b></td>"),
    @("<td><b>📡 Protocols</b></td>", "<td><b>Protocols</b></td>"),
    @("<td><b>📚 RAG & Embeddings</b></td>", "<td><b>RAG & Embeddings</b></td>"),
    @("<td><b>🖥️ Frontend</b></td>", "<td><b>Frontend</b></td>"),
    @("<td><b>💾 Persistence</b></td>", "<td><b>Persistence</b></td>"),
    @("<td><b>🔍 Search & Tools</b></td>", "<td><b>Search & Tools</b></td>"),
    @("<td><b>📊 Evaluation</b></td>", "<td><b>Evaluation</b></td>"),
    @("<td><b>⚡ ML / Deep Learning</b></td>", "<td><b>ML / Deep Learning</b></td>"),
    @("> **💡 Ideas for contributions:**", "> **Ideas for contributions:**"),
    @("<h3>⭐ If this repo helped you", "<h3>If this repo helped you"),
    @("Built with ❤️ by", "Built by")
)

foreach ($pair in $replacements) {
    $content = $content.Replace($pair[0], $pair[1])
}
[IO.File]::WriteAllText((Resolve-Path "README.md").Path, $content, [System.Text.Encoding]::UTF8)
